config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get :about, to: 'about#show'
  get :contact, to: 'contact#show'
  resources :laptops, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'laptops/index'
  # get 'laptops/show'

  resources :carts, only: [:index, :create, :destroy], as: 'carts' do
    member do
      patch 'update_quantity', to: 'carts#update_quantity'
    end
  end


  root "laptops#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/about.rb
class About < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["title", "content", "created_at", "updated_at", "message_cont", "message_eq", "message_start", "message_end", "History_cont", "History_eq", "History_start", "History_end"]
  end
  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "id", "id_value", "message", "name", "updated_at"]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :region

  validates :first_name, :last_name, :email, :address, :password, presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 6}
end

app/models/laptop.rb
class Laptop < ApplicationRecord
  validates :laptop_name, :brand, :model, :price, :processor, :ram, :storage, :operating_system, :gpu, :size, presence: true
  validates :price, :size, numericality: { greater_than_or_equal_to: 0 }
  validates :sale_price, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  attribute :on_off_sale, :boolean, default: false
  has_one_attached :image

  has_many :order_items
  has_many :orders, through: :order_items
  def self.ransackable_associations(auth_object = nil)
    ["order_items", "orders"]
  end
  def self.ransackable_attributes(auth_object = nil)
    ["brand", "created_at", "gpu", "id", "id_value", "laptop_name", "model", "on_off_sale", "operating_system", "price", "processor", "ram", "sale_price", "size", "storage", "updated_at", "image_attachment_id_eq", "image_blob_id_eq", "description"]
  end


end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :laptops, through: :order_items

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "order_date", "total", "updated_at"]
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :laptop

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "laptop_id", "order_id", "quantity", "unit_price", "updated_at"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
  validates :province_name, :pst, :gst, :hst, presence: true
  validates :province_name, uniqueness: true

  has_many :users

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "gst", "hst", "id", "id_value", "province_name", "pst", "updated_at"]
  end

  def to_s
    province_name
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   belongs_to :province
   has_many :orders

   validates :province_id, presence: true

   def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "email", "encrypted_password", "first_name", "id", "id_value", "province_id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["orders", "province"]
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
    @about = About.all.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :initialize_session
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :cart

  def initialize_session
    session[:shopping_cart] ||= []
    session[:quantities] ||= {}
  end

  def cart
    Laptop.find(session[:shopping_cart])
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :address, :province_id])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :address, :province_id])
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def create
    logger.debug("Adding #{params[:id]}")
    id = params[:id].to_i
    session[:shopping_cart] << id unless session[:shopping_cart].include?(id)
    laptop = Laptop.find(id)
    flash[:notice] = "+ #{laptop.laptop_name} added to cart."
    redirect_to root_path
  end

  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    # session[:quantities].delete(id.to_s) if session[:quantities][id.to_s]

    if session[:quantities][id.to_s]
      session[:quantities].delete(id.to_s)
    end

    laptop = Laptop.find(id)
    flash[:notice] = "- #{laptop.laptop_name} removed from cart."
    redirect_back(fallback_location: root_path)
  end

  def update_quantity
    laptop_id = params[:id].to_i
    quantity = params[:quantity].to_i

    session[:quantities][laptop_id] = quantity
    redirect_to carts_path
  end

  def index
    @cart_items = []
    session[:shopping_cart].each do |item_id|
      laptop = Laptop.find_by(id: item_id)
      @cart_items << laptop if laptop
    end
    @total_price = @cart_items.sum(&:price)
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
    @contact = Contact.all.first
  end
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  def index
    @brands = Laptop.distinct.pluck(:brand)
    @laptops = Laptop.all.order("price DESC").page(params[:page]).per(50)

    if params[:sale].present?
      @laptops = Laptop.where(on_off_sale: true).page(params[:page]).per(50)
    end

    if params[:new].present?
      @laptops = Laptop.where("created_at >= ?", 1.hour.ago).page(params[:page]).per(50)
    end

    if params[:updated].present?
      @laptops = Laptop.where("updated_at >= ?", 1.hour.ago).page(params[:page]).per(50)
    end

  end

  def show
    @laptop = Laptop.find(params[:id])
  end

  def search
    @brands = Laptop.distinct.pluck(:brand)

    if params[:keywords].present? || params[:brand] != "All Brands"
      wildcard_search = "%#{params[:keywords]}%"
      @laptops = Laptop.where("laptop_name LIKE ?", wildcard_search).page(params[:page]).per(16)

      if params[:brand] != "All Brands"
       @laptops = @laptops.where(brand: params[:brand])
      end
    else
      @laptops = Laptop.all.order("price DESC").page(params[:page]).per(50)
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/views/about/show.html.erb
<h1 class="title has-text-centered">About Us</h1>
<div class="content">
  <h2 class="subtitle">Message</h2>
  <p><%= @about.message %></p>
</div>

<div class="content">
  <h2 class="subtitle">History</h2>
  <p><%= @about.History %></p>
</div>

app/views/carts/index.html.erb
<section>
  <% if cart.present? %>
    <ul>
      <% cart.each do |l| %>
        <li class="level-right">
          <%= l.laptop_name %>
          <%= form_with url: update_quantity_cart_path(l.id), method: :patch do |form| %>
            <div class="control">
              <%= number_field_tag :quantity, session[:quantities][l.id.to_s] || 1, class: 'input is-small', min: 1, style: 'width: 4em;' %>
              <%= form.submit 'Update', class: 'button is-small is-info' %>
            </div>
          <% end %>
            <%= button_to 'Remove', cart_path(l.id), method: :delete %>
        </li>
      <% end %>
    </ul>
  <% end %>
</section>
<section class="is-flex is-flex-direction-column is-align-items-center">
  <div class="mb-3">
    Sub-Total: <%= number_to_currency(@total_price) %>
  </div>
  <div>
    <%= button_to 'Order' %>
  </div>
</section>

app/views/common/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="#navbarMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarMenu" class="navbar-menu">

    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>
      <%= link_to "About", about_path, class: "navbar-item" %>
      <%= link_to "Contact", contact_path, class: "navbar-item" %>
      <% if user_signed_in? %>
        <%= link_to "Cart(#{session[:shopping_cart].length})", carts_path, class: "navbar-item" %>
      <% end %>
    </div>

    <div class="navbar-end">
      <% if user_signed_in? %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-item" %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: "navbar-item" %>
        <%= button_to "Login", new_user_session_path, class: "navbar-item", method: :get %>
      <% end %>
    </div>
  </div>
</nav>

app/views/contact/show.html.erb
<h1 class="title has-text-centered">Contact Us</h1>
<div class="contact-info">
  <p><strong>Name:</strong> <%= @contact.name %></p>
  <p><strong>Email:</strong> <%= @contact.email %></p>
</div>
<div class="contact-message">
  <p><strong>Message:</strong></p>
  <p><%= @contact.message %></p>
</div>

app/views/laptops/index.html.erb
<link rel="stylesheet" type="text/css" href="laptops.css">
<%= form_with(url: search_laptops_path, method: :get, local: true) do |form| %>
  <div class="field is-inline">
    <%= text_field_tag(:keywords, nil, class:"input", placeholder: 'Search for Laptop') %>
    <%= select_tag(:brand, options_for_select(['All Brands'] + @brands), class: "select") %>
    <%= submit_tag("Search", class: "button is-primary is-square") %>
  </div>
<% end %>

<%= form_with(url: root_path, method: :get, local: true, id: "sale-form") do |form| %>
  <div class="checkboxes-horizontal">
    <%= check_box_tag "sale", "1", params[:sale].present?, class: "checkbox", onchange: "this.form.submit()" %>
    <%= label_tag "sale", "Sale" %>
  </div>
<% end %>

<%= form_with(url: root_path, method: :get, local: true, id: "new-form") do |form| %>
  <div class="checkboxes-horizontal">
    <%= check_box_tag "new", "1", params[:new].present?, class: "checkbox", onchange: "this.form.submit()" %>
    <%= label_tag "new", "New" %>
  </div>
<% end %>

<%= form_with(url: root_path, method: :get, local: true, id: "new-form") do |form| %>
  <div class="checkboxes-horizontal">
    <%= check_box_tag "updated", "1", params[:updated].present?, class: "checkbox", onchange: "this.form.submit()" %>
    <%= label_tag "updated", "Updated" %>
  </div>
<% end %>

<h1 class="title has-text-centered">Available Laptops</h1>
  <div class="columns is-multiline">
    <% @laptops.each do |laptop| %>
    <div class="column is-one-sixth">
      <div class="box laptop-box">
      <% if laptop.image.present? %>
        <div class="laptop-image"><%= image_tag(laptop.image, size: '200x200')%></div>
      <% else %>
        <div class="laptop-image-placeholder"></div>
      <% end %>
        <div class="laptop-name"> <%= link_to laptop.brand + ' ' + laptop.laptop_name, laptop %> -
        <% if laptop.on_off_sale? %>
          $<%= number_with_delimiter(number_with_precision(laptop.sale_price, precision: 2)) %> </div>
        <% else %>
          $<%= number_with_delimiter(number_with_precision(laptop.price, precision: 2)) %> </div>
        <% end %>
        <% if user_signed_in? %>
          <div>
            <% if cart.include?(laptop) %>
              <%= button_to cart_path(laptop), method: :delete do %>
              Remove from Carts
              <% end %>
            <% else %>
              <%= form_with url: carts_path, method: :post do %>
                <%= hidden_field_tag(:id, laptop.id) %>
                <%= button_tag 'Add to Cart' %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
<%= paginate @laptops %>

app/views/laptops/search.html.erb
<link rel="stylesheet" type="text/css" href="laptops.css">
<%= form_with(url: search_laptops_path, method: :get, local: true) do |form| %>
  <div class="field is-inline">
    <%= text_field_tag(:keywords, nil, class:"input", placeholder: 'Search for Laptop') %>
    <%= select_tag(:brand, options_for_select(['All Brands'] + @brands), class: "select") %>
    <%= submit_tag("Search", class: "button is-primary is-square") %>
  </div>
<% end %>

<h1 class="title has-text-centered">Available Laptops</h1>
  <div class="columns is-multiline">
    <% @laptops.each do |laptop| %>
    <div class="column is-one-tenth">
      <div class="box laptop-box">
      <% if laptop.image.present? %>
        <div class="laptop-image"><%= image_tag(laptop.image, size: '200x200')%></div>
      <% else %>
        <div class="laptop-image-placeholder"></div>
      <% end %>
        <div class="laptop-name"> <%= link_to laptop.brand + ' ' + laptop.laptop_name, laptop %> - $<%= number_with_delimiter(number_with_precision(laptop.price, precision: 2)) %> </div>
        <div>
          <% if cart.include?(laptop) %>
            <%= button_to cart_path(laptop), method: :delete do %>
            Remove from Cart
            <% end %>
          <% else %>
            <%= form_with url: carts_path, method: :post do %>
              <%= hidden_field_tag(:id, laptop.id) %>
              <%= button_tag 'Add to Cart' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

<%= paginate @laptops %>

app/views/laptops/show.html.erb
<div class="container">
 <div class="columns is-centered">
  <div class="column is-half">
   <div class="box">
    <h1 class="title has-text-centered"><%= @laptop.brand %> <%= @laptop.laptop_name %></h1>
      <div class="has-text-centered">
       <% if @laptop.image.present? %>
        <%= image_tag(@laptop.image, size: '200x200')%>
       <% end %>
      </div>
      <p>This product is a <%= @laptop.model %> laptop.
       It features a <%= @laptop.processor %> CPU, <%= @laptop.gpu %> GPU, <%= @laptop.ram %> of RAM, and <%= @laptop.storage %> of storage.
       It runs on the <%= @laptop.operating_system %> operating system.
       <%= @laptop.description %>
       </p>
      <div class="content">
       <p class="has-text-weight-bold">Laptop Features:</p>
       <p><%= @laptop.model %></p>
       <p>$<%= number_with_delimiter(number_with_precision(@laptop.price, precision: 2)) %></p>
       <p><%= @laptop.processor %></p>
       <p><%= @laptop.ram %></p>
       <p><%= @laptop.storage %></p>
       <p><%= @laptop.operating_system %></p>
       <p><%= @laptop.gpu %></p>
      </div>
     </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>EcommerceProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
  </head>

  <body>

    <%= render partial: 'common/header' %>
    <%#= debug session[:shopping_cart] %>
    <%#= debug session[:quantities] %>
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
    <section class="section">
      <div class="container">
      </div>
    <%= yield %>
    </section>
  </body>
</html>